config/routes.rb
Rails.application.routes.draw do
  resources :cars

  devise_for :users
  get 'static_pages/home'

  get 'static_pages/about'

  root to: "static_pages#home"

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "profile", to: "devise/registrations#edit"
    get "sign_out", to: "devise/sessions#destroy"
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
	belongs_to :user

	validates :user_id, presence: true

	def model_description
		(model_year || "") + " " + (model_make || "") + " " + (model || "") + " " + (model_trim || "")
	end
end

app/models/select_option.rb
class SelectOption < ActiveRecord::Base

	validates :domain, :code_value, :display_value, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, :display_name, :display_name_lower,
  	:length => {:minimum => 1, :maximum => 64}

  # validates :email, :presence => true, 
  #                   :length => {:minimum => 3, :maximum => 254},
  #                   :uniqueness => true,
  #                   :format => {:with => /\A(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Z‌​a-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}\Z/i}
	validates :email, presence: true, 
	    length: {minimum: 3, maximum: 254},
	    uniqueness: true,
	    format: {with: /\A(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Z‌​a-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}\Z/i}

  validates :display_name_lower, uniqueness: true

  has_many :cars

  before_validation :set_display_name_lower

  private
    def set_display_name_lower
      self.display_name_lower = (self.display_name || "").downcase
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :display_name

    @new_user_columns = [:first_name, :last_name, :display_name, :email,
      :password, :password_confirmation]

  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user! #, only: [:new, :create]
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :model_years_create, only: [:new, :edit, :create]

  # GET /cars
  # GET /cars.json
  def index
    @cars = current_user.cars
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    # Set the user id the currently signed in user.
    car.user_id = current_user

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    def model_years_create
      @model_years = []
      (Date.today.year+1).downto(1931).each do |year|
        @model_years << year
      end
      
      @state_select_options =  [['California', 'CA'], ['Oregon', 'OR']]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:user_id, :vin, :license_state, :license_number,
       :distance_unit, :fuel_unit, :location_id,
       :model_year, :model_make, :model, :model_trim, :vehicle_type, :engine, :drive_type, :body_style, :doors)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return the bootstrap class for the flash
	def bootstrap_class_for flash_type
	    case flash_type
	      when :success, "success"
	        "alert-success"
	      when :error, "error"
	        "alert-danger"
	      when :alert, "alert"
	        "alert-warning"
	      else
	        "alert-info"
	    end
	end

	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Fuel My Maintenance"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size = 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.display_name, class: "gravatar")
  end
end

app/views/cars/_form.html.erb
<hr>
<%= form_for(@car, html: {class: "form-inline", role: "form"}) do |f| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%# Print the label %>
    <%#= f.label :vin, class: "control-label col-sm-1" %>
    <%#= f.label :model_year, class: "control-label col-sm-1" %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">VIN Year Make Model Trim</h3>
    </div>
    <div class="panel-body">

     <div class="form-group input-group">
        <%# Create the input %>
        <% field_options = {"class" => "form-control", "id" => "inputVIN",  "placeholder" => "VIN"} %>    
        <%= f.text_field :vin, field_options %>
        <span class="input-group-btn">
          <button class="btn btn-default skinny-button" type="button" id="vin-lookup-button" >
            <span class="glyphicon glyphicon-cloud-download"></span></button>
        </span>

    </div>
    <div class="form-group input-group" >
      <%= f.text_field :model_year, class: "form-control", placeholder: "Year", size: "4" %>
      <span class="input-group-btn">
        <button class="btn btn-default skinny-button" type="button" id="year-lookup-button" data-toggle="modal" data-target="#YearPickModal">
          <span class="glyphicon glyphicon-chevron-down"></span></button>
      </span>
    </div>
    <%#
    <div class="form-group">
      <%= f.select :model_year, options_for_select( @model_years), class: "form-control" %>
    <%# </div> %>
    <div class="form-group input-group">
      <%= f.text_field :model_make, class: "form-control", placeholder: "Make", size: "12" %>
      <span class="input-group-btn">
        <button class="btn btn-default skinny-button" type="button" id="make-lookup-button" data-toggle="modal" data-target="#MakePickModal">
          <span class="glyphicon glyphicon-chevron-down"></span></button>
      </span>
    </div>

    <div class="form-group">
      <%= f.text_field :model, class: "form-control", placeholder: "Model", size: "12" %>
    </div>
    <div class="form-group">
      <%= f.text_field :model_trim, class: "form-control", placeholder: "Trim" %>
    </div>
  </div>
</div>


  <fieldset>
    <legend> License </legend>
    <div class="form-group">
      <%= f.label :license_state %><br>
      <%= f.text_field :license_state %>
      <%= f.select :license_state, options_for_select( @state_select_options ) %>
    </div>
    <div class="form-group">
      <%= f.label :license_number %><br>
      <%= f.text_field :license_number %>
    </div>
  </fieldset> 

  <div class="field">
    <%= f.label :distance_unit %><br>
    <%= f.text_field :distance_unit %>
  </div>
  <div class="field">
    <%= f.label :fuel_unit %><br>
    <%= f.text_field :fuel_unit %>
  </div>

  <div class="field">
    <%= f.label :location_id %><br>
    <%= f.text_field :location_id %>
  </div>

  <div class="field">
    <%= f.label :vehicle_type %><br>
    <%= f.text_field :vehicle_type %>
  </div>
  <div class="field">
    <%= f.label :engine %><br>
    <%= f.text_field :engine %>
  </div>
  <div class="field">
    <%= f.label :drive_type %><br>
    <%= f.text_field :drive_type %>
  </div>
  <div class="field">
    <%= f.label :body_style %><br>
    <%= f.text_field :body_style %>
  </div>
  <div class="field">
    <%= f.label :doors %><br>
    <%= f.text_field :doors %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= "<input type='hidden' id='edmunds_api_key' value='#{Rails.application.secrets.edmunds_api_key}'>".html_safe %>
  </div>

<% end %>

  
<!-- Modal window for picking the year -->
<div class="modal" id="YearPickModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Year</h4>
      </div>
      <div class="modal-body">
        <div class="decades">
          <% @model_years.each do |year| %>
            <% if year == @model_years.first || year.to_s[3] == '0'%>
              <div class="decade">
            <% end %>
            <%= "<a href='#{year}'>#{year}</a>".html_safe %>
            <% if year.to_s[3] == '1' %>
              </div>
            <% end %>
          <% end %>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Needed Year Is Not Displayed Above</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal window for picking the make and model -->
<div class="modal" id="MakePickModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="MakePickModalLabel">Test</h4>
      </div>
      <div class="modal-body" id="MakePickModalBody">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Needed Choice Is Not Displayed Above</button>
      </div>
    </div>
  </div>
</div>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars for <%= current_user.display_name %></h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Vin</th>
      <th>License state</th>
      <th>License number</th>
      <th>Location</th>
      <th>Model Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.user.display_name %></td>
        <td><%= car.vin %></td>
        <td><%= car.license_state %></td>
        <td><%= car.license_number %></td>
        <td><%= car.location_id %></td>
        <td><%= car.model_description %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @car.user_id %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>License state:</strong>
  <%= @car.license_state %>
</p>

<p>
  <strong>License number:</strong>
  <%= @car.license_number %>
</p>

<p>
  <strong>Distance unit:</strong>
  <%= @car.distance_unit %>
</p>

<p>
  <strong>Fuel unit:</strong>
  <%= @car.fuel_unit %>
</p>

<p>
  <strong>Location:</strong>
  <%= @car.location_id %>
</p>

<p>
  <strong>Model year:</strong>
  <%= @car.model_year %>
</p>

<p>
  <strong>Model make:</strong>
  <%= @car.model_make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Model trim:</strong>
  <%= @car.model_trim %>
</p>

<p>
  <strong>Vehicle type:</strong>
  <%= @car.vehicle_type %>
</p>

<p>
  <strong>Engine:</strong>
  <%= @car.engine %>
</p>

<p>
  <strong>Drive type:</strong>
  <%= @car.drive_type %>
</p>

<p>
  <strong>Body style:</strong>
  <%= @car.body_style %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @car.doors %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/_flash_messages.html.erb
<%# In application.html.erb add "= render 'layouts/flash_messages' 
     this code also requires the "bootstrap_class_for() helper " %>
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert"> <span class="glyphicon glyphicon-remove"></span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_icon_menu.html.erb
<div class="navbar-wrapper">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">

      <div class="navbar-header">
        <%#-- Button to contain the menu options when the menu is collapsed. %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%=  %>
        <%#-- Link to the icon %>
        <%= link_to image_tag("gas-nozzle-icon-no-bg.png", alt: "Brand Text", size: "100x100") + " Fuel My Maintenance", static_pages_home_path, class: "navbar-brand" %>
      </div>

      <%# Class to designate the menu below is pulled into the collapse button menu %>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "About", static_pages_about_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%# Start the drop down menu section %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "About", static_pages_about_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>

            <%# Start the user signed in down menu section %>
            <li class="dropdown navbar-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= gravatar_for( current_user, 24) + sanitize(" &diams; ") + current_user.display_name %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profile", profile_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", sign_out_path %></li>
              </ul>
            </li>

          <% else %>
            <%= form_for(:user, url: session_path(:user), html: {class: "nav navbar-form navbar-right", role: "form"}) do |f| %>
              <div class="form-group">
                <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
              </div>
              <%= f.submit "Sign in", class: "btn btn-success" %>
            <% end %>
          <% end %>
        </ul>
      </div>      
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%# menu with the icon %>
	<%= render 'layouts/icon_menu' %>

	<%# Bootstrap formating %>
    <div class="container-fluid">
    	<div class="row">
    		<div class="col-md-offset-2 col-md-8">
				  <%# flash-messages-partial %>
				  <%= render 'layouts/flash_messages' %>
        </div>
			</div>
      <div class="row">
        <div class="col-md-2 car-panel">
          cars
        </div>
        <div class="col-md-8 main-panel">

			   <%= yield %>
		    </div>
        <div class="col-md-2 advertising-panel">
          ads
        </div>
      </div>
    </div>
  </div>		
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
	<h1>StaticPages#home</h1>
	<h4>Find me in app/views/static_pages/home.html.erb</h4>
	<% if user_signed_in? %>
		<%= gravatar_for( current_user, 120 ) %>
	<% else %>
		<%= link_to '<button type="button" class="btn btn-primary">Sign Up</button>'.html_safe, sign_up_path %>
	<% end %>